In [ ]:
# importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mlt
import seaborn as sns

In [ ]:
#reading csv file using pyhton
raw_df=pd.read_csv("/content/loan_data.csv")

In [ ]:
#checking information present in this
raw_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   credit.policy      9578 non-null   int64
 1   purpose            9578 non-null   object
 2   int.rate           9578 non-null   float64
 3   installment        9578 non-null   float64
 4   log.annual.inc     9578 non-null   float64
 5   dti                9578 non-null   float64
 6   fico               9578 non-null   int64
 7   days.with.cr.line  9578 non-null   float64
 8   revol.bal          9578 non-null   int64
 9   revol.util         9578 non-null   float64
 10  inq.last.6mths     9578 non-null   int64
 11  delinq.2yrs        9578 non-null   int64
 12  pub.rec            9578 non-null   int64
 13  not.fully.paid     9578 non-null   int64
dtypes: float64(6), int64(7), object(1)
memory usage: 1.0+ MB

In [ ]:
raw_df.head()

,credit.policy,purpose,int.rate,installment,log.annual.inc,dti,fico,days.with.cr.line,revol.bal,revol.util,inq.last.6mths,delinq.2yrs,pub.rec,not.fully.paid
0,1,debt_consolidation,0.1189,829.10,11.350407,19.48,737,5639.958333,28854,52.1,0,0,0,0
1,1,credit_card,0.1071,228.22,11.082143,14.29,707,2760.000000,33623,76.7,0,0,0,0
2,1,debt_consolidation,0.1357,366.86,10.373491,11.63,682,4710.000000,3511,25.6,1,0,0,0
3,1,debt_consolidation,0.1008,162.34,11.350407,8.10,712,2699.958333,33667,73.2,1,0,0,0
4,1,credit_card,0.1426,102.92,11.299732,14.97,667,4066.000000,4740,39.5,0,1,0,0

In [ ]:
#the column names are not understandable. also we need to understand the data.
#understanding each column
#credit.policy=meets lending club criteria(it is present as 1 and 0)
#purpose=purpose of taking loan
#int.rate=interest rate
#installment=monthly payment amount
#log.annual.inc=the natural log of annual income
#dti=debt-to-income ratio
#fico=credit score(higher fico=better grade)
#days.with.cr.line=days the borrower has had a credit line
#revol.bal=unpaid credit balance
#revol.util=percentage of credit line used
#inq.last.6mths=credit inquiries in last 6 months
#deling.2yrs=times 30+ days past due in last 2 years
#pub.rec=number of derogatory public records
#not.fully.paid=default status(given in 0 and 1)

In [ ]:
#the column names need to be changed to make them more understandable
#this i have done using excel and the data given in 0s and 1s has been changed to "yes"/"no" and "paid back"/"defaulted" accordingly
#credit.policy(0=no,1=yes)-->meets_credit_policy
#purpose=loan_purpose
#int.rate=interest_rate
#installment=monthly_installment
#log.annual.inc=the natural log of annual income
#dti=dti_ratio
#days.with.cr.line=credit_history_days
#revol.bal=revolving_balance
#revol.util=credit_utilization_rate
#inq.last.6mths=recent_credit_inquiries
#deling.2yrs=past_due_2yrs
#pub.rec=public_records
#not.fully.paid(0=paid back,1=defaulted)=default_status

In [ ]:
#because the annual income was in natural logarithm form i created a new column namely annual_income used formula =EXP(E2) it converted the log form into $ .then added one more column named it income_band divided the annual income into different categories using formula =IFS(F2<=30000, "Low Income (<$30k)", F2<=60000, "Medium-Low ($30k-$60k)", F2<=100000, "Medium-High ($60k-$100k)", F2>100000, "High Income (>$100k)") then we were provided with fico score therefore i created a column named loan_grade according to the fico scores divided grades into a,b,c,d using formula =IF(I2>=750,"Grade A(Excellent Risk)",IF(I2<=749,"Grade B(Very Good Risk)",IF(I2>=660,"Grade C(Good Risk)","Grade D(Below High Risk")))

In [ ]:
data_df=pd.read_excel("/content/loan_data_new.xlsx")

In [ ]:
data_df.describe()

,interest_rate,monthly_installment,log.annual.inc,annual_income(in $),dti_ratio,fico,credit_history_days,revolving_balance,credit_utilization_rate,recent_credit_inquiries,pat_due_2yrs,public_records
count,9578.000000,9578.000000,9578.000000,9.578000e+03,9578.000000,9578.000000,9578.000000,9.578000e+03,9578.000000,9578.000000,9578.000000,9578.000000
mean,0.122640,319.089413,10.932117,6.840203e+04,12.606679,710.846314,4560.767197,1.691396e+04,46.799236,1.577469,0.163708,0.062122
std,0.026847,207.071301,0.614813,6.122753e+04,6.883970,37.970537,2496.930377,3.375619e+04,29.014417,2.200245,0.546215,0.262126
min,0.060000,15.670000,7.547502,1.896000e+03,0.000000,612.000000,178.958333,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,0.103900,163.770000,10.558414,3.850000e+04,7.212500,682.000000,2820.000000,3.187000e+03,22.600000,0.000000,0.000000,0.000000
50%,0.122100,268.950000,10.928884,5.576400e+04,12.665000,707.000000,4139.958333,8.596000e+03,46.300000,1.000000,0.000000,0.000000
75%,0.140700,432.762500,11.291293,8.012100e+04,17.950000,737.000000,5730.000000,1.824950e+04,70.900000,2.000000,0.000000,0.000000
max,0.216400,940.140000,14.528354,2.039784e+06,29.960000,827.000000,17639.958330,1.207359e+06,119.000000,33.000000,13.000000,5.000000

In [ ]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   meets_credit_policy      9578 non-null   object
 1   loan_purpose             9578 non-null   object
 2   interest_rate            9578 non-null   float64
 3   monthly_installment      9578 non-null   float64
 4   log.annual.inc           9578 non-null   float64
 5   annual_income(in $)      9578 non-null   float64
 6   income_band              9578 non-null   object
 7   dti_ratio                9578 non-null   float64
 8   fico                     9578 non-null   int64
 9   loan_grade               9578 non-null   object
 10  credit_history_days      9578 non-null   float64
 11  revolving_balance        9578 non-null   int64
 12  credit_utilization_rate  9578 non-null   float64
 13  recent_credit_inquiries  9578 non-null   int64
 14  pat_due_2yrs             9578 non-null   int64
 15  public_records           9578 non-null   int64
 16  default_status           9578 non-null   object
dtypes: float64(7), int64(5), object(5)
memory usage: 1.2+ MB

In [ ]:
data_df.columns

Index(['meets_credit_policy', 'loan_purpose', 'interest_rate',
       'monthly_installment', 'log.annual.inc', 'annual_income(in $)',
       'income_band', 'dti_ratio', 'fico', 'loan_grade', 'credit_history_days',
       'revolving_balance', 'credit_utilization_rate',
       'recent_credit_inquiries', 'pat_due_2yrs', 'public_records',
       'default_status'],
      dtype='object')

In [ ]:
data_df.head()

,meets_credit_policy,loan_purpose,interest_rate,monthly_installment,log.annual.inc,annual_income(in $),income_band,dti_ratio,fico,loan_grade,credit_history_days,revolving_balance,credit_utilization_rate,recent_credit_inquiries,pat_due_2yrs,public_records,default_status
0,Yes,debt_consolidation,0.1189,829.10,11.350407,85000.000385,Medium-High ($60k-$100k),19.48,737,Grade B(Very Good Risk),5639.958333,28854,52.1,0,0,0,Paid Back
1,Yes,credit_card,0.1071,228.22,11.082143,65000.000073,Medium-High ($60k-$100k),14.29,707,Grade B(Very Good Risk),2760.000000,33623,76.7,0,0,0,Paid Back
2,Yes,debt_consolidation,0.1357,366.86,10.373491,31999.999943,Medium-Low ($30k-$60k),11.63,682,Grade B(Very Good Risk),4710.000000,3511,25.6,1,0,0,Paid Back
3,Yes,debt_consolidation,0.1008,162.34,11.350407,85000.000385,Medium-High ($60k-$100k),8.10,712,Grade B(Very Good Risk),2699.958333,33667,73.2,1,0,0,Paid Back
4,Yes,credit_card,0.1426,102.92,11.299732,80799.999636,Medium-High ($60k-$100k),14.97,667,Grade B(Very Good Risk),4066.000000,4740,39.5,0,1,0,Paid Back

In [ ]:
data_df.duplicated().sum()

np.int64(0)

In [ ]:
data_df.isnull().sum()

meets_credit_policy        0
loan_purpose               0
interest_rate              0
monthly_installment        0
log.annual.inc             0
annual_income(in $)        0
income_band                0
dti_ratio                  0
fico                       0
loan_grade                 0
credit_history_days        0
revolving_balance          0
credit_utilization_rate    0
recent_credit_inquiries    0
pat_due_2yrs               0
public_records             0
default_status             0
dtype: int64

In [ ]:
#the data is cleaned